# .github/workflows/snake.yml
name: Update GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'      # daily at midnight UTC
  push:
    branches: [ main, master ]

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate dark SVG-only Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # output to output/github-snake-dark.svg, using the dark palette
          outputs: |
            output/github-snake-dark.svg?palette=github-dark

      - name: Commit updated snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-snake-dark.svg
          git commit -m "chore: update github-snake-dark.svg" || echo "No changes to commit"
          git push
