name: Generate Snake
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write  # Give push access

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3.2.0
        with:
          github_user_name: sri-ganeshk
          palette: default
          color_snake: '#00ff00'
          color_dots: '#ffffff'

      - name: Check generated files
        run: ls -la  # Check if snake.svg is generated

      - name: Commit and push the snake.svg
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push

