name: Update GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
      - master

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate GitHub Snake
        uses: Platane/snk@v1
        with:
          # Your GitHub username
          github_user_name: sri-ganeshk
          # Where to write the SVG
          svg_out_path: output/github-snake.svg
          # Any extra snk CLI args—here we set the snake color
          args: --color 79,195,247

      - name: Commit updated snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-snake.svg
          git commit -m "chore: update github-snake.svg" || echo "No changes to commit"
          git push
