name: Update GitHub Snake

on:
  # every day at 00:00 UTC
  schedule:
    - cron: '0 0 * * *'
  # also on push to main/master so it runs immediately after you add it
  push:
    branches:
      - main
      - master

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate GitHub Snake
        uses: Platane/snk@v1
        with:
          # where to write the snake SVG
          path: output/github-snake.svg
          # you can customize the snake color here:
          color: 79,195,247

      - name: Commit updated snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-snake.svg
          git commit -m "chore: update github-snake.svg" || echo "No changes to commit"
          git push
